### ISSUE TITLE
Operation validation errors don't get reported to client properly

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#101]
reported by @psmir 

When client side validation fails my promise receives the convenient Hyperstack::Operation::ValidationException. But when server side validation fails it receives plain Exception and I can't get errors hash from it. Moreover the server responds with code 500.
Is it possible to make Hyperstack to raise Hyperstack::Operation::ValidationException on the client side when server validation fails and not to respond with code 500 ?

**Comment by psmir** [comment]
Same thing applies to abort! and failed { }
```
Hyperstack::Operation
  step { abort!({error: "some description"}) }
end
```
In the promise I receive an object with class Hyperstack::Operation::Exit
and can fetch the errors hash like this
```
.fail {|e| e.result } 
```

Hyperstack::ControllerOp responds with code 500

the promise receives plain Exception with the message {"error":"Hyperstack::Operation::Exit"}
```
Hyperstack::Operation
  step { fail }
  failed do
    {error: "some description"}
  end
end
```
```
# returns !!Hash !! {"error"=>"some description"}
#
.fail {|e| puts "!!#{e.class} !! #{e}" }
```
Hyperstack::ControllerOp responds with code 500 and the promise receives plain Exception with the message {"error"=>"some description"}

**Comment by catmando** [comment]
so just to confirm... the big problem here is that you resulting error type does not match the message type you got on the client?

**Comment by catmando** [comment]
I think Validation errors should be a 400, authentication errors be a 403, and all other errors should stay as 500 errors:

500 Internal Server Error

A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.

**Comment by psmir** [comment]
Thank you for the fix. I have tested it and found out that some inconsistencies are still there.

1) Validation
```
class SignUpOp < Hyperstack::Operation
  param :email, type: String
  param :password, type: String
  param :password_confirmation, type: String
  
   validate do
     add_error(
       :password_confirmation,
       :doesnt_match,
       "Your new password and confirmation do not match"
     ) unless params.password == params.password_confirmation
   end
end

# In some component

SignUpOp.run(email: nil, password: 'aaa', password_confirmation: 'bbb')
.fail do |e|
  puts e.errors.class    # Mutations::ErrorHash
  puts e.errors.symbolic # {"email"=>"required", "password_confirmation"=>"doesnt_match"}
  puts e.errors.message  # {"email"=>"email is required", "password_confirmation"=>"Your new password and confirmation do not match"}
  
  # if I change the base operation class to Hyperstack::ControllerOp
  
  puts e.errors.class    # Mutations::ErrorArray (we need Mutations::ErrorHash here)
  puts e.errors.symbolic # required,doesnt_match
  puts e.errors.message  # email is required,Your new password and confirmation do not match  
                          
end
```

2) abort!
```
class SignUpOp < Hyperstack::Operation

  step do 
    h = { some_key: 'aaa' }
    abort! h
  end

end

SignUpOp.run()
.fail do |e|
  puts e.class           # Hyperstack::Operation::Exit
  puts e.result          # {"some_key"=>"aaa"}
  puts e.result[:key]    # aaa
  
  # if I change the base operation class to Hyperstack::ControllerOp
  puts e.class           # Hyperstack::Operation::Exit
  puts e.result          # nothing
end
```
3) failed {}
```
class SignUpOp < Hyperstack::Operation
  step { fail! }
  failed do
    { some_key: 'aaa' }
  end
end

SignUpOp.run()
.fail do |e|
  puts e.class       # Hash
  puts e             # {"some_key"=>"aaa"}
  puts e[:some_key]  # aaa
  
  # if I change the base operation class to Hyperstack::ControllerOp
  puts e.class       # Hash
  puts e             # {}
end
```

**Comment by catmando** [comment]
@psmir thanks for making this clear.   I'll have a chance to work on this once I get this Rails Conf presentation sent in.
