### ISSUE TITLE
ActiveRecord::Base.find should raise error not return nil

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#118]
For example  `Participant.find(177)` will in Rails raise

`ActiveRecord::RecordNotFound: Couldn't find Participant with 'id'=177`

and so should we.

(see https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/activerecord/lib/active_record/errors.rb#L56) for details on errors, maybe we should just paste in class?

**Comment by Tim-Blokdijk** [comment]
Also .find won't take an array with id's. I will add a new issue for this.

**Comment by catmando** [comment]
I am not sure this is a good idea.  The first react pass it would return a dummy id, then the next react pass it would throw an error.  Seems weird. Change to discussion.

**Comment by Tim-Blokdijk** [comment]
I implemented the .find([id_array]) function in such a way that it is returning nil. The tests I wrote for it also test for this behavior.
My suggestion would be to keep returning "nil" records and not raise errors. Unless someone has a clear rational why raising errors is better.

**Comment by catmando** [comment]
Leaving it the way it is
