### ISSUE TITLE
Rails template for installation 

### ISSUE THREAD

**Issue by barriehadfield** [hyperstack-org/hyperstack#12]
Create Rails template for installation which gets its gems from the Hyperstack edge branch

Add HelloWorld Component and tests

**Comment by barriehadfield** [comment]
@johansmitsnl when using the repo for Gems, you have advised:

```
gem 'hyper-component', :glob => 'ruby/hyper-component/hyper-component.gemspec', branch: 'edge', :git => 'https://github.com/hyperstack-org/hyperstack'
```

which requires that the gem be built and checked into the repo, yet we have a `.gitignore` which is excluding `.gem`

Are you OK with me changing the `.gitignore` and building and committing the gems?

**Comment by johansmitsnl** [comment]
Why does it need the gemfile to be included? It looks for the gemspec only
