### ISSUE TITLE
ActiveRecord::Base#new? should be #new_record?

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#120]
deprecate `new?` and replace with `new_record?` which is the ActiveRecord method name.

**Comment by catmando** [comment]
needed to use new? for #117 so this got done with that.

**Comment by catmando** [comment]
I don't see any reason to deprecate.  Its just an alias method

**Comment by Tim-Blokdijk** [comment]
Seems to work, issue can be closed.
Does not need explicit documentation, as it's a ActiveRecord method.
