### ISSUE TITLE
pre-rendering support should be optional

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#150]
Because it depends on mini-racer which does not work for windows developers (and there may be other cases as well) we should make pre-rendering somehow optional.

Prerendering itself is optional, but the dependency on mini-racer is in the gem regardless.

Either we could make prerendering a separate gem, or (i kind of like this) remove the dependency on mini-racer, and just auto detect it.  If its there we will use it if not prerendering gets switched off.

I think this is easy enough to do that we should get into 1.0

I also marked it as good first issue, because I think detecting mini-racer and changing the prerendering option to :off, is probably just a couple of lines of code.

**Comment by Tim-Blokdijk** [comment]
As far as I know mini-racer is incompatible with jRuby.
Pages like https://github.com/jruby/jruby/wiki/C-Extension-Alternatives point to https://github.com/cowboyd/therubyrhino as an alternative that is jRuby compatible.
But therubyrhino seems to be incompatible with MRI..

Not having this dependency could be a good first step I think.

**Comment by catmando** [comment]
Mini racer dependency removed
