### ISSUE TITLE
Huge public columns hash

### ISSUE THREAD

**Issue by sfcgeorge** [hyperstack-org/hyperstack#162]
The database information Hyperstack includes on the page is huge for our app with >50 models. Noticeably slows down pageload. 

https://gist.github.com/sfcgeorge/80bbb475e7613b85823a885cc1b2aedf

**Comment by Tim-Blokdijk** [comment]
I get a 404 on your gist link?

**Comment by sfcgeorge** [comment]
My bad, fixed. I've also just noticed that the public columns hash is actually included multiple times - once per mounted component! That's surely not helping the page size.

**Comment by catmando** [comment]
@sfcgeorge - so you are mounting multiple components in the view?

A short term fix that is easy but not elegant is to manually put in some erb method to dump the hash and then patch it out of the hyperstack code.

For ease of initial integration render_component runs assuming its the only one on the page, so dumps the hash.  IIRC I could not find any way to only do it once so to speak but I could be wrong about that too.

If one copy of the hash is still too big, perhaps it gets rendered as a seperate asset in production and the whole gzip mechanism compress it?

Let me know if you need assistance, but I'll assume you can work around it for now?

**Comment by catmando** [comment]
In the next point release we will do something to make this better:

1) instead of just dumping the raw public columns data, we will put it in a minimalist data set that has only what Hyperstack needs. 
2) The dump will be in a standard format so it doesn't matter if rails changes how the columns data works, we will have a consistent API
3) Either make it so it dumps once, (i.e. only on first component mount) and if not possible, then provide a mechanism to manually dump it.

**Comment by sfcgeorge** [comment]
Yep, mounting multiple. 

1. Sounds great.
2. Really good thought for stability.
3. All I can think for automatically doing the right thing is a request local variable (if there is such a Rails thing... https://edgeapi.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) or maybe even just an ivar `@columns_data_rendered = true`. Or a manual option ala `render_component(schema: false)`

**Comment by sfcgeorge** [comment]
I added this patch to [ComponentMount](https://github.com/hyperstack-org/hyperstack/blob/3bbfb6eaf2948c57b9a351c700f299e9fdc664ad/ruby/hyper-component/lib/hyperstack/internal/component/rails/component_mount.rb#L46). Page size went from 739 KB to 317 KB, nice! An ivar feels a bit wrong but it works. (note it's the `react_component` method that's impacted by this, `render_component` in the controller is fine as there's only ever one).

```ruby
def footers
  unless @hyperstack_footers_rendered
    @hyperstack_footers_rendered = true
    Hyperstack::Component::IsomorphicHelpers.prerender_footers(controller)
  end
end
```

**Comment by catmando** [comment]
updated per @sfcgeorge suggestion:

https://github.com/hyperstack-org/hyperstack/blob/a39ae68a9317abb6cbe37e32b98abf54b1ebf751/ruby/hyper-component/lib/hyperstack/internal/component/rails/component_mount.rb#L45
