### ISSUE TITLE
ActiveRecord::Base.find([1,2,3]) should return mutiple records

### ISSUE THREAD

**Issue by Tim-Blokdijk** [hyperstack-org/hyperstack#184]
Currently ActiveRecord::Base.find([1,2,3]) returns a single record.
Should be an array of multiple records. 
https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find

**Comment by catmando** [comment]
Things I didn't know!

**Comment by catmando** [comment]
Implementing should be straight forward:  

```ruby 
def find(*args)
  args = args[0] if args[0].is_a? Array
  return args.collect { |id| find(id) } if args.count > 1
   # do whatever find does now with args[0]
   ...
end
```

note this will deal with `find(1)`, `find(1, 2, 3)` and `find([1, 2, 3])` all of which are legal.

**Comment by Tim-Blokdijk** [comment]
Seems to be defined at:
https://github.com/hyperstack-org/hyperstack/blob/edge/ruby/hyper-model/lib/reactive_record/active_record/class_methods.rb#L62

**Comment by Tim-Blokdijk** [comment]
Finally got around to this.
`
def find(*args)
    args = args[0] if args[0].is_a? Array
    return args.collect { |id| find(id) } if args.count > 1
    find_by(primary_key => args[0])
end
`
Seems to work. In Hyperstack ActiveRecord#find returns a nil if record is not found. In Rails it raises a ActiveRecord::RecordNotFound exception. I'm OK with this behavior, but we could also filter out the nil values when returning an array?

Still have to write a testcase, hope to push a pull request for this in the coming days.
