### ISSUE TITLE
hyperstack-rails gem

### ISSUE THREAD

**Issue by janbiedermann** [hyperstack-org/hyperstack#19]

**Comment by janbiedermann** [comment]
default:
opal-webpack-loader
hyper-store
hyper-component
hyper-router
hyper-transport
hyper-transport-store-redis
hyper-transport-actioncable
hyper-model
hyper-operation*
hyper-spec*

optional:
hyper-policy or hyper-pundit
hyper-international
hyper-transport-pusher

*not sure, maybe optional

**Comment by barriehadfield** [comment]
Issue tracked elsewhere
