### ISSUE TITLE
Update slack invitation link.

### ISSUE THREAD

**Issue by gadimbaylisahil** [hyperstack-org/hyperstack#258]
Slack invitation link is expired on the website. Please update it :pray:

**Comment by barriehadfield** [comment]
@gadimbaylisahil thank you for raising this; we are looking into this now. I suspect Slack have change the way their invite links work. I will keep you posted as soon as this resolved.

**Comment by barriehadfield** [comment]
Hi @gadimbaylisahil sorry, I have not been able to fix this on this site today, but for now use this link: 

https://join.slack.com/t/hyperstack-org/shared_invite/enQtNTg4NTI5NzQyNTYyLWQ4YTZlMGU0OGIxMDQzZGIxMjNlOGY5MjRhOTdlMWUzZWYyMTMzYWJkNTZmZDRhMDEzODA0NWRkMDM4MjdmNDE

I will update the site with the new link tomorrow.

**Comment by stonetwig** [comment]
The link worked, but it is still the wrong one on the website? :)

Thanks
