### ISSUE TITLE
The link in the description, https://www.hyperstack.org does not work

### ISSUE THREAD

**Issue by alex-min** [hyperstack-org/hyperstack#290]
Hi there,

Just a small issue to tell you that  https://www.hyperstack.org should probably be replaced to  https://hyperstack.org in the description

**Comment by barriehadfield** [comment]
Hi, @alex-min thanks for that. Where is the www.hyperstack.org link?

**Comment by alex-min** [comment]
In the description on the top

![Screenshot_2019-12-31 hyperstack-org hyperstack](https://user-images.githubusercontent.com/1898825/71608376-61501500-2bb3-11ea-831f-304deba017d8.png)

**Comment by barriehadfield** [comment]
Thank you very much - changed that.
