### ISSUE TITLE
 merge all repos in the new tree structure

### ISSUE THREAD

**Issue by barriehadfield** [hyperstack-org/hyperstack#3]
What I'm testing at the moment is what if you want to include a gem from Git that is in a folder.
This can be done by using:
```
#https://bundler.io/guides/git.html
gem 'hyperstack-react', :git => 'https://github.com/hyperstack-org/hyperstack', :glob => 'ruby/hyperstact-react/*.gemspec', branch: 'edge'
```
Currently I'm checking how to manage the version number (share for all languages) and the CI setup.
In favour of the speed I want to create a matrix for each component, this allows it to test all gems in parallel but the whole job will be validated over all individual jobs.
Also want to test several Ruby versions to see if we might brake something in the future of a version in the past. Due to the project not being a Ruby only project I have to do some magic to resolve this, but all doable.
On tags all will be released to the appropriate destinations, gems, npm, etc... with all the same version for consistency and it will be a hard lock on the version '= 2.0.0' so that upgrades go in lockstep.
So some testing to do until I want to finalize it.
Also this needs to be explained in the README so that people that end up on the repo understands it.

Create Repo labels for each component

**Comment by barriehadfield** [comment]
@johansmitsnl @johan-smits considering one of our top-level goals is to have one language for all code (meaning the front-end and back-end code), and considering we all believe we are likely to embrace crystal next, would it not make sense to have the repo language specific (instead of a top-level folder in the repo for the language)?

That would give:

+ `hyperstack-ruby`
+ `hyperstack-crystal`
+ etc

**Comment by catmando** [comment]
Also very much prefer option 2

**Comment by johansmitsnl** [comment]
Option 2 is integrated in: https://github.com/hyperstack-org/hyperstack/tree/edge/ruby

CI/CD still needs to be added

**Comment by sfcgeorge** [comment]
[thought I sent this yesterday, might be a bit late now]

If I've followed, I think what this means is 2 big repos (frontend and backend) with nested folders for core sub-projects. These would all have their own gemspecs, exactly as Rails does things with the top level Rails and folders for ActiveModel, ActiveRecord etc.

Being somewhat language agnostic makes it slightly more complicated, I guess we'd have the 2 core repos being low level, then thin wrappers for specific languages and frameworks (initially Opal and Rails).

And finally some auxiliary projects that aren't so tightly coupled to anything, again like Rails has in their org separate repos for things like JBuilder.

Something like:

```
hyperstack-client
hyperstack-client/hyperstack-operation
hyperstack-client/hyperstack-model
hyperstack-client/hyperstack-store
hyperstack-client/hyperstack-component
hyperstack-client/hypercetera...

hyperstack-client-opal
hyperstack-client-opal/hyperstack-record

[hyperstack-client-javascript] (Perhaps later, nice Typescript version or something)

hyperstack-server
hyperstack-server/hyperstack-operation
hyperstack-server/hyperstack-model
hyperstack-client/hypercetera...

hyperstack-server-rails
hyperstack-server-rails/hyperstack-record

[hyperstack-server-sinatra]
```

This would assume the client is written in pure Javascript to enable the Opal wrapper to be optional, but that's likely an unreasonably big rewrite (and I think most of core don't want to write pure JS).

And the server would be Ruby, but if there's to be a Crystal or C# version then maybe it should be `hyperstack-server-ruby` and `hyperstack-server-crystal` etc.
