### ISSUE TITLE
Broken handling of rejected promises in Operation

### ISSUE THREAD

**Issue by kvechera** [hyperstack-org/hyperstack#300]
There is a broken behavior of the Operation object when its step runs another Operation or Promise. If the nested operation fails, the outer operation is interrupted without executing a failure track and finishes as resolved promise instead of rejected.

```
class TestOperation < Hyperstack::Operation
	step { Promise.new.tap{|p| p.reject 'bad' } }
	step { puts "step 2" }
	failed { puts "failed 1" }
end
TestOperation.run.then{|result| puts "then #{result}"}.fail{|error| puts "fail #{error}"}
# Got:
# => then bad
# Expected:
# => failed 1
# => fail bad
```

The similar problem is seen if we handle then/fail branches of a promise inside a step (it's broken either for `fail` method, or for `abort!` and `raise` an exception):
```
class TestOperation < Hyperstack::Operation
	step {
		Promise.new.tap{|p| p.reject 'bad' }
		.fail{|err|
			puts "step 1 promise fail: #{err}"
			fail err
		}
	}
	step { puts "step 2" }
	failed { puts "failed 1" }
end

TestOperation.run.then{|result| puts "then #{result}"}.fail{|error| puts "fail #{error}"}
# Got:
# => step 1 promise fail: bad
# => then bad
# Expected:
# => step 1 promise fail: bad
# => failed 1
# => fail
```

The same behavior is seen when we use a chained Operation instead of Promise.
Tested with the edge branch [c0f18b016124] / 1.0.alpha1.5.
Ruby version:  2.4.1p111, Opal 0.11.4 (Firefox 66)

**Comment by catmando** [comment]
Thanks this just got fixed in alpha1.7
