### ISSUE TITLE
Release new gem version due to libv8 difficulties

### ISSUE THREAD

**Issue by reedstonefood** [hyperstack-org/hyperstack#306]
Installing the current version of `rails-hyperstack` requires installing `libv8`. It needs version 6.7, which does not have a native version on darwin-19 (Catalina), so it has to build it, which consistently fails. There are many gists, github comments etc. that try to help with this but I've had no success so far.

I believe this issue could be solved by releasing a new version of the gem. This is because since `1.0.alpha1.5` was released, there has been a [change to use the latest version of libv8](https://github.com/hyperstack-org/hyperstack/commit/da5ddfd84044b258f9303e384ebaa71b04405d5e). This _does_ have a darwin-19 version [available](https://rubygems.org/gems/libv8/versions/7.3.492.27.1-x86_64-darwin-19), so should be much more straightforward to install.

**Comment by sgtmacdiesel** [comment]
I'm having this issue as well.

**Comment by catmando** [comment]
removed all dependencies on libv8
