### ISSUE TITLE
template looks like an ordinary rails template

### ISSUE THREAD

**Issue by adisciple50** [hyperstack-org/hyperstack#336]
listed instructions for installation produces the following output.

i did this in windows powershell: 
rails new MyApp -T -m https://rawgit.com/hyperstack-org/hyperstack/edge/install/rails-webpacker.rb
puma
bundle install

and it just looks like an ordinary rails app. the documentation does not tell me to include the rails-hyperstack framework. but i willl do now

**Comment by catmando** [comment]
duplicate of #338
