### ISSUE TITLE
The `regulate_instance_collections` block should be able to return a truthy value to indicate `connect to self`

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#352]
currently you have to say `regulate_instance_connections { self if admin? }` for example, instead of just saying

`regulate_instance_collections { admin? }` 

why can't the regulation just treat any truthy value, that is not an instance of the class or the enumerable as just self?

**Comment by mpantel** [comment]
> currently you have to say `regulate_instance_collections { self if admin? }` for example, instead of just saying
> 
> `regulate_instance_collections { admin? }`
> 
> why can't the regulation just treat any truthy value, that is not an instance of the class or the enumerable as just self?

regulate_instance_connections that is...

**Comment by catmando** [comment]
After looking at the code, and thinking about this, it needs to stay as is.  The problem is that hyper-operation assumes very little about the objects representing channels, so there is no real way to tell if some truthy value represents just "true" or represents a channel that should be connected to.
