### ISSUE TITLE
Pre-render not working

### ISSUE THREAD

**Issue by barriehadfield** [hyperstack-org/hyperstack#42]
Sample app which uses pre-rendering for a simple Component (using hyperloop-legacy gems)

Error: `window is not defined` on startup.

Sample here: https://github.com/barriehadfield/prerender-not-working

To reproduce:
`bundle`
`yarn`
`foreman start`

Perhps there is a missing documentation step to stop the import of Jquery? I tried removing it from application.js but that made no difference.

**Comment by catmando** [comment]
Sometime back we all decided that prererendering is off by default.

Switch it by adding
`config.prerendering = :on`
to the hyperloop.rb initializer

If this works please close.
