### ISSUE TITLE
React warning when deployed to production - Alpha 1.2

### ISSUE THREAD

**Issue by barriehadfield** [hyperstack-org/hyperstack#66]
React warning when deployed to production (same warning not seen in development mode)

`Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named 'defaultProps' instead.`

See https://edge.hyperstack.org/ for example.

**Comment by catmando** [comment]
ugh

**Comment by catmando** [comment]
@barriehadfield can you check to see if this still happens in the wip 1.3 branch?  (miracles might occur)

**Comment by catmando** [comment]
This must be something specific with a component library used in the hyperstack.org website.  It does not occur with other apps (i.e. www.catprint.com) when deployed to production
