### ISSUE TITLE
add param_accessor_style :accessors

### ISSUE THREAD

**Issue by catmando** [hyperstack-org/hyperstack#74]
which will create snake case param method accessors.

The underlying `@CamelCased` ivars will still exist, so these will just be low-toll wrappers to the ivars.

Eventually we will decide if we want to keep the `@CamelCase` as the default.

**Comment by camelCaseD** [comment]
FYI you pulled me into this. Please be careful what you type. If the above is suppose to be code surround it with back ticks

**Comment by catmando** [comment]
fixed, sorry to disturb!

**Comment by catmando** [comment]
closed.  see hyper-component/spec/client_features/param_declaration_spec.rb `it "can use accessor style param names"` for example

**Comment by catmando** [comment]
In summary here are how params look for the three options:

```ruby
class Index < HyperComponent
  param_accessor_style :accessors
  param :scope  # scope instance variable is automatically created

  render(SECTION, class: :main) do
    UL(class: 'todo-list') do
      scope.each { |todo| TodoItem(todo: todo) }
    end
  end
end
```

with the legacy params wrapper:

```ruby
class Index < HyperComponent
  param_accessor_style :legacy
  param :scope  # params are accessed via the params wrapper

  render(SECTION, class: :main) do
    UL(class: 'todo-list') do
      params.scope.each { |todo| TodoItem(todo: todo) }
    end
  end
end
```

and the default:

```ruby
class Index < HyperComponent
  param_accessor_style :hyperstack # default!
  param :scope  # params are accessed via the camelized instance var

  render(SECTION, class: :main) do
    UL(class: 'todo-list') do
      @Scope.each { |todo| TodoItem(todo: todo) }
    end
  end
end
```
