### ISSUE TITLE
can the owl build process refer Hyper.valid_* for models?

### ISSUE THREAD

**Issue by janbiedermann** [hyperstack-org/hyperstack#8]
rails keep models in app/models
hyper keeps models in app/hyperstack/models
we need to guard models anyway, Hyperstack.valid_* is used, can we use that in the build process, so that models can stay in app/models and only those in Hyperstack.valid_* get included on the client?

**Comment by johansmitsnl** [comment]
This would be very intuitive

**Comment by barriehadfield** [comment]
Issue tracked elsewhere
